### ISSUE TITLE
Cart JS | Step 2

### ISSUE THREAD

**Issue by zmicer-rasko** [Multyjog/sk.github.io#16]
1. After clicking on cart user must:
- see list of products with
 - title
 - quantity
 - price
 - weight
- be able to remove product from cart "X"
- be able to change product quantity "-"/"+", minimum 1.

Extra:
2. Use 3rd party flash messages library (use any from https://www.jqueryscript.net/blog/Best-Toast-Notification-jQuery-Plugins.html). Show 2 kind of messages:
- product added to cart
- product removed to cart.

Messages should disappear after N seconds by themselves automatically and there's should be "X" on message for manual removing.

Remove message should be neutrally styled (usually gray colors are used).
Adding message should be positively styled (usually green/blue colors used).

**Comment by Multyjog** [comment]
### TODO before implementing

- [ ] Add support for product weight from server
- [ ] Add support adding multiple products (quantity)
- [ ] Store information about products added to cart
- [ ] Add flash messages library

**Comment by Multyjog** [comment]
###TODO implementing steps

- [ ] Currently, i doesn't know,yet

**Comment by Multyjog** [comment]
@zmicer-rasko 
What is gonna be, when user click's on button second time?
I have some variants: 

- add 1 more product quantity in cart
- Nothing, because after first click button set unactive and change the color
- nothing is happen 

Please, choose 1 and reply
